version: '3.8'

services:
    nginx:
        container_name: auto-group-nginx
        build:
            context: .docker/nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./auto-group:/var/www/auto-group
        depends_on:
            - php-fpm

    php-fpm:
        container_name: auto-group-php-fpm
        build:
            context: .docker/php-fpm
            dockerfile: Dockerfile
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
        volumes:
            - ./auto-group:/var/www/auto-group
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=mysql"
            - "MYSQL_USER=mysql"
            - "MYSQL_PASSWORD=mysql"
            - "MYSQL_DATABASE=auto-group"
        ports:
            - "33061:3306"

volumes:
    postgres:
